//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.1
//     from Assets/Scripts/Controlls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @Controlls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @Controlls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Controlls"",
    ""maps"": [
        {
            ""name"": ""Touch"",
            ""id"": ""06cd54d0-8bb0-48f6-a8a7-ccdb236d49bb"",
            ""actions"": [
                {
                    ""name"": ""PrimaryContatct"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0334a624-6fbb-417c-b438-89be4bf797b1"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PrimaryPos"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0972982f-985a-436b-82cd-27f754736e9e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""9d514d6b-6026-4a66-a32a-844f23d64b4f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryContatct"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a856661-cd4a-44eb-830a-fb1aa4a43c56"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PrimaryPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch
        m_Touch = asset.FindActionMap("Touch", throwIfNotFound: true);
        m_Touch_PrimaryContatct = m_Touch.FindAction("PrimaryContatct", throwIfNotFound: true);
        m_Touch_PrimaryPos = m_Touch.FindAction("PrimaryPos", throwIfNotFound: true);
    }

    ~@Controlls()
    {
        UnityEngine.Debug.Assert(!m_Touch.enabled, "This will cause a leak and performance issues, Controlls.Touch.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch
    private readonly InputActionMap m_Touch;
    private List<ITouchActions> m_TouchActionsCallbackInterfaces = new List<ITouchActions>();
    private readonly InputAction m_Touch_PrimaryContatct;
    private readonly InputAction m_Touch_PrimaryPos;
    public struct TouchActions
    {
        private @Controlls m_Wrapper;
        public TouchActions(@Controlls wrapper) { m_Wrapper = wrapper; }
        public InputAction @PrimaryContatct => m_Wrapper.m_Touch_PrimaryContatct;
        public InputAction @PrimaryPos => m_Wrapper.m_Touch_PrimaryPos;
        public InputActionMap Get() { return m_Wrapper.m_Touch; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(TouchActions set) { return set.Get(); }
        public void AddCallbacks(ITouchActions instance)
        {
            if (instance == null || m_Wrapper.m_TouchActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_TouchActionsCallbackInterfaces.Add(instance);
            @PrimaryContatct.started += instance.OnPrimaryContatct;
            @PrimaryContatct.performed += instance.OnPrimaryContatct;
            @PrimaryContatct.canceled += instance.OnPrimaryContatct;
            @PrimaryPos.started += instance.OnPrimaryPos;
            @PrimaryPos.performed += instance.OnPrimaryPos;
            @PrimaryPos.canceled += instance.OnPrimaryPos;
        }

        private void UnregisterCallbacks(ITouchActions instance)
        {
            @PrimaryContatct.started -= instance.OnPrimaryContatct;
            @PrimaryContatct.performed -= instance.OnPrimaryContatct;
            @PrimaryContatct.canceled -= instance.OnPrimaryContatct;
            @PrimaryPos.started -= instance.OnPrimaryPos;
            @PrimaryPos.performed -= instance.OnPrimaryPos;
            @PrimaryPos.canceled -= instance.OnPrimaryPos;
        }

        public void RemoveCallbacks(ITouchActions instance)
        {
            if (m_Wrapper.m_TouchActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ITouchActions instance)
        {
            foreach (var item in m_Wrapper.m_TouchActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_TouchActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public TouchActions @Touch => new TouchActions(this);
    public interface ITouchActions
    {
        void OnPrimaryContatct(InputAction.CallbackContext context);
        void OnPrimaryPos(InputAction.CallbackContext context);
    }
}
